# Generated by Django 5.2.6 on 2025-11-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='department',
            field=models.CharField(blank=True, choices=[('Financial Cyber Crime', 'Financial Cyber Crime'), ('Social Media Crime', 'Social Media Crime'), ('E-commerce & Online Fraud', 'E-commerce & Online Fraud'), ('Government & Critical Infrastructure Attacks', 'Government & Critical Infrastructure Attacks'), ('Corporate / Business Cyber Crime', 'Corporate / Business Cyber Crime'), ('Healthcare Cyber Crime', 'Healthcare Cyber Crime'), ('Education Sector Crime', 'Education Sector Crime'), ('Telecommunication Crime', 'Telecommunication Crime'), ('Entertainment & Copyright Crime', 'Entertainment & Copyright Crime'), ('Transportation & Automotive Cyber Crime', 'Transportation & Automotive Cyber Crime'), ('IoT / Smart Device Cyber Crime', 'IoT / Smart Device Cyber Crime'), ('Cloud Cyber Crime', 'Cloud Cyber Crime'), ('Cryptocurrency / Blockchain Crime', 'Cryptocurrency / Blockchain Crime'), ('Mobile-Based Cyber Crime', 'Mobile-Based Cyber Crime'), ('Email & Communication Crime', 'Email & Communication Crime'), ('Cyber Terrorism', 'Cyber Terrorism'), ('Cyber Espionage', 'Cyber Espionage'), ('Personal Cyber Crime', 'Personal Cyber Crime'), ('Dark Web Crime', 'Dark Web Crime'), ('Industrial/Manufacturing Cyber Crime', 'Industrial/Manufacturing Cyber Crime')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('UPI Fraud', 'UPI Fraud'), ('Online Banking Fraud', 'Online Banking Fraud'), ('Credit/Debit Card Fraud', 'Credit/Debit Card Fraud'), ('Unauthorized Bank Transfer', 'Unauthorized Bank Transfer'), ('Investment Scam', 'Investment Scam'), ('Online Shopping Fraud', 'Online Shopping Fraud'), ('Loan App Scam', 'Loan App Scam'), ('Phishing', 'Phishing'), ('Spear Phishing', 'Spear Phishing'), ('Email Spoofing', 'Email Spoofing'), ('Business Email Compromise', 'Business Email Compromise'), ('Identity Theft', 'Identity Theft'), ('SIM Swapping', 'SIM Swapping'), ('Impersonation', 'Impersonation'), ('Cyberstalking', 'Cyberstalking'), ('Cyberbullying', 'Cyberbullying'), ('Account Hacked', 'Account Hacked'), ('Revenge Porn', 'Revenge Porn'), ('Data Breach', 'Data Breach'), ('Ransomware', 'Ransomware'), ('Malware Attack', 'Malware Attack'), ('Insider Attack', 'Insider Attack'), ('Government Portal Hacked', 'Government Portal Hacked'), ('Public Service Disruption', 'Public Service Disruption'), ('Infrastructure Attacks', 'Infrastructure Attacks'), ('Phone Cloning', 'Phone Cloning'), ('Mobile Spyware', 'Mobile Spyware'), ('Malicious Apps', 'Malicious Apps'), ('IoT Device Hacking', 'IoT Device Hacking'), ('Smart Home Intrusion', 'Smart Home Intrusion'), ('CCTV Hacking', 'CCTV Hacking'), ('Cloud Account Hacking', 'Cloud Account Hacking'), ('Cloud Server Breach', 'Cloud Server Breach'), ('Cyber Terrorism', 'Cyber Terrorism'), ('Cyber Espionage', 'Cyber Espionage'), ('Dark Web Threat', 'Dark Web Threat'), ('Blackmailing', 'Blackmailing'), ('Online Threat', 'Online Threat'), ('Unknown Malware', 'Unknown Malware'), ('Piracy', 'Piracy'), ('Vehicle GPS Hacking', 'Vehicle GPS Hacking'), ('Industrial Machine Hacking', 'Industrial Machine Hacking'), ('Other', 'Other')], max_length=50),
        ),
    ]
